# Generated by Django 4.2.7 on 2023-12-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='liftChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('benchPR', models.IntegerField(blank=True, null=True, verbose_name='Enter new bench press record')),
                ('ohpPR', models.IntegerField(blank=True, null=True, verbose_name='Enter new overhead press record')),
                ('squatPR', models.IntegerField(blank=True, null=True, verbose_name='Enter new squat record')),
                ('deadliftPR', models.IntegerField(blank=True, null=True, verbose_name='Enter new deadlift record')),
            ],
            options={
                'db_table': 'lifts',
            },
        ),
    ]
