# Generated by Django 4.2.7 on 2023-12-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_liftchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=3)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=3)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.RenameModel(
            old_name='liftChart',
            new_name='liftModel',
        ),
        migrations.RenameModel(
            old_name='progressChart',
            new_name='progressModel',
        ),
    ]
